"""add llm_call_logs

Revision ID: 5fa31230c997
Revises: 0c31c3a1e6ad
Create Date: 2026-07-14 19:44:52.829004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fa31230c997'
down_revision: Union[str, Sequence[str], None] = '0c31c3a1e6ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_call_logs',
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('token_prompt', sa.Integer(), nullable=True),
    sa.Column('token_completion', sa.Integer(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_llm_call_logs_created_at'), 'llm_call_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_llm_call_logs_project_id'), 'llm_call_logs', ['project_id'], unique=False)
    op.create_index(op.f('ix_llm_call_logs_user_id'), 'llm_call_logs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_llm_call_logs_user_id'), table_name='llm_call_logs')
    op.drop_index(op.f('ix_llm_call_logs_project_id'), table_name='llm_call_logs')
    op.drop_index(op.f('ix_llm_call_logs_created_at'), table_name='llm_call_logs')
    op.drop_table('llm_call_logs')
    # ### end Alembic commands ###
