"""add knowledge_files content_hash

Revision ID: 7076816516e4
Revises: 39198eaeea5d
Create Date: 2026-07-17 09:22:16.266296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7076816516e4'
down_revision: Union[str, Sequence[str], None] = '39198eaeea5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('knowledge_files', sa.Column('content_hash', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_knowledge_files_content_hash'), 'knowledge_files', ['content_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_knowledge_files_content_hash'), table_name='knowledge_files')
    op.drop_column('knowledge_files', 'content_hash')
    # ### end Alembic commands ###
