"""add section version

Revision ID: 9635d2dc22d6
Revises: a20f16f0da4e
Create Date: 2026-07-14 18:09:23.082195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9635d2dc22d6'
down_revision: Union[str, Sequence[str], None] = 'a20f16f0da4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sections', sa.Column('version', sa.Integer(), server_default='1', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sections', 'version')
    # ### end Alembic commands ###
